version: '3.8'

services:
  # Simplified Temporal setup
  temporal:
    image: temporalio/auto-setup:latest
    ports:
      - "7233:7233"
      - "8081:8080"  # Temporal Web UI on port 8081
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
    depends_on:
      - postgresql
    networks:
      - temporal-network

  # Database
  postgresql:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=temporal
      - POSTGRES_USER=temporal
      - POSTGRES_DB=temporal
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=scram-sha-256
    volumes:
      - temporal_db_data:/var/lib/postgresql/data
    networks:
      - temporal-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - temporal-network

networks:
  temporal-network:
    driver: bridge

volumes:
  temporal_db_data:
  redis_data:
